// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaIb-8F0Lj1UeDBsreJHjav1Svqyoagws',
    appId: '1:284740078250:web:b0871aadf53804e7e19ed3',
    messagingSenderId: '284740078250',
    projectId: 'projectnewtest-57620',
    authDomain: 'projectnewtest-57620.firebaseapp.com',
    storageBucket: 'projectnewtest-57620.appspot.com',
    measurementId: 'G-KJ2JZP1GYN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7mtGglCWEWoShU89DT6ZR7wbPHxYP18o',
    appId: '1:284740078250:android:2ce0e91063a8962ce19ed3',
    messagingSenderId: '284740078250',
    projectId: 'projectnewtest-57620',
    storageBucket: 'projectnewtest-57620.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACbYpwfbZEGcsgPPY2ZSZGRddVKfJZe3o',
    appId: '1:284740078250:ios:417e7beded804ae7e19ed3',
    messagingSenderId: '284740078250',
    projectId: 'projectnewtest-57620',
    storageBucket: 'projectnewtest-57620.appspot.com',
    iosClientId: '284740078250-npr9qq1sh87e99hiomluu8ipq64hcchu.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFacebookResponsiveUi',
  );
}
